INSERT INTO PERSON (ID, NAME, FAMILY, USERNAME, PASSWORD, BIRTH_DATE, PHONENUMBER)
VALUES (1, 'Mehdi', 'Ahmadi', 'mehdi', 'mypassword', TO_DATE('1990-05-15', 'YYYY-MM-DD'), '09123456789');

SELECT * FROM PERSON WHERE USERNAME = 'mehdi123';


SELECT * FROM PERSON;

COMMIT;