CREATE TABLE PERSONS
(
    ID          NUMBER PRIMARY KEY,
    NAME        NVARCHAR2(30),
    FAMILY      NVARCHAR2(30),
    USERNAME    NVARCHAR2(20) UNIQUE NOT NULL,
    PASSWORD    NVARCHAR2(20),
    BIRTH_DATE  DATE,
    PHONE_NUMBER NVARCHAR2(15)
);

CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;

--

CREATE TABLE TRANSACTIONS
(
    ID         NUMBER PRIMARY KEY,
    PERSON_ID REFERENCES PERSONS,
    AMOUNT NUMBER,
    TRANSACTION_TYPE VARCHAR(7),
    DATE_TIME TIMESTAMP
);

CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;

--

CREATE VIEW TRANSACTION_REPORT AS
    SELECT
        T.ID AS TRANSACTION_ID,
        P.ID AS PERSON_ID,
        P.NAME,
        P.FAMILY,
        P.USERNAME,
        P.PASSWORD,
        P.BIRTH_DATE,
        P.PHONE_NUMBER,
        T.AMOUNT,
        T.TRANSACTION_TYPE,
        T.DATE_TIME AS TRANSACTION_DATE_TIME
FROM TRANSACTIONS T
JOIN PERSONS P on T.PERSON_ID = P.ID;